<a href="https://colab.research.google.com/github/Devansh-0/Sentiment-Analysis-/blob/main/Sentiment_Analysis_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np 
import pandas as pd 
import re
import nltk 

In [ ]:
data_source_url = "https://raw.githubusercontent.com/kolaveridi/kaggle-Twitter-US-Airline-Sentiment-/master/Tweets.csv"
airline_tweets = pd.read_csv(data_source_url)

In [ ]:
airline_tweets.head()

In [ ]:
features = airline_tweets.iloc[:, 10].values
labels = airline_tweets.iloc[:, 1].values

In [ ]:
processed_features = []

for sentence in range(0, len(features)):
 
    processed_feature = re.sub(r'\W', ' ', str(features[sentence]))

   
    processed_feature= re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_feature)

    
    processed_feature = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_feature) 

  
    processed_feature = re.sub(r'\s+', ' ', processed_feature, flags=re.I)

   
    processed_feature = re.sub(r'^b\s+', '', processed_feature)

   
    processed_feature = processed_feature.lower()

    processed_features.append(processed_feature)

In [ ]:
! pip install nltk
import nltk
nltk.download('stopwords')



In [ ]:
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer (max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('english'))
processed_features = vectorizer.fit_transform(processed_features).toarray()

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(processed_features, labels, test_size=0.2, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
text_classifier.fit(X_train, y_train)

In [ ]:
predictions = text_classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[1723  108   39]
 [ 326  248   40]
 [ 132   58  254]]
              precision    recall  f1-score   support

    negative       0.79      0.92      0.85      1870
     neutral       0.60      0.40      0.48       614
    positive       0.76      0.57      0.65       444

    accuracy                           0.76      2928
   macro avg       0.72      0.63      0.66      2928
weighted avg       0.75      0.76      0.74      2928

0.7599043715846995


In [ ]:
!pip intall steamlit
!pip install pyngrok
from pyngrok import ngrok

ERROR: unknown command "intall" - maybe you meant "install"
  Created wheel for pyngrok: filename=pyngrok-5.0.0-cp36-none-any.whl size=18780 sha256=197a41db787b28eeec9879460c920df4d934937f585155a2606107e518f2e2f2
  Stored in directory: /root/.cache/pip/wheels/95/df/23/af8dde08c3fcdc7b966adcacef48ab29aa3b0b1860df5d2b79
Successfully built pyngrok


In [ ]:
%%writefile app.py
import streamlit as st
st.title('Sentiment Analysis')


Overwriting app.py
